#!/bin/bash

LANGUAGE="${LANGUAGE:-${LANG%%_*}}"

if [[ "$LANGUAGE" == "pt" ]]; then
    MSG_REMOVED="Flatctl removido."
else
    MSG_REMOVED="Flatctl removed."
fi

APP_NAME="flatctl"

rm -rf "$HOME/.local/share/$APP_NAME"
rm -f "$HOME/.local/bin/$APP_NAME"
rm -f "$HOME/.local/bin/uninstall-flatctl"
rm -f "$HOME/.local/share/applications/$APP_NAME.desktop"

printf "%s\n" "$MSG_REMOVED"
