#!/bin/bash

# SCRIPT: frontend
# DESCRIÇÃO: Camada de apresentação para
# o script flatctl - yad --form


DISPATCHER="$BASE_DIR/router/dispatcher"


yad --form \
    --title="Flatctl" \
    --class="$APP_NAME" \
    --window-icon="$FLATPAK_LOGO" \
    --text="<span $TITLE_STYLE>$(t APP_TITLE)</span><span $DESCRIPTION_STYLE>$(t APP_DESCRIPTION)</span>" \
    --image="$FLATPAK_LOGO" \
    --borders=20 \
    --button="$(t BTN_EXIT)"!gtk-quit \
    --button="$(t BTN_ABOUT)"!gtk-about:"$DISPATCHER about" \
    --buttons-layout=edge \
    --width=600 \
    --fixed \
    --columns=2 \
    --text-align="left" \
    --field="  <b>$(t BTN_SEARCH)</b>!$ICON_SEARCH!$(t TOOLTIP_SEARCH):FBTN" "$DISPATCHER search" \
    --field="  <b>$(t BTN_UPDATE)</b>!$ICON_UPDATE!$(t TOOLTIP_UPDATE):FBTN" "$DISPATCHER update"\
    --field="  <b>$(t BTN_MAINTENANCE)</b>!$ICON_MAINTENANCE!$(t TOOLTIP_MAINTENANCE):FBTN" "$DISPATCHER maintenance" \
    --field="  <b>$(t BTN_UNINSTALL)</b>!$ICON_UNINSTALL!$(t TOOLTIP_UNINSTALL):FBTN" "$DISPATCHER uninstall" \
    --field="  <b>$(t BTN_LIST)</b>!$ICON_LIST!$(t TOOLTIP_LIST):FBTN" "$DISPATCHER list" 
