#!/bin/bash

# SCRIPT: flatpak_functions
# DESCRIÇÃO: Contém as funções para o flatctl


function create_fifo
{
    local dir fifo
    
    dir=$(mktemp -d) || return 1
    fifo="$dir/fifo"
    
    mkfifo -m 600 "$fifo" ||
    {
        rm -rf "$dir"
        return 1
    }
    
    printf "%s\n" "$fifo"
}


function cleanup_fifo
{
    rm -rf "${1%/*}"
}


function register_task_pid
{
    local pid=$1
    printf "%s\n" "$pid" >> "$PID_FILE"
}


function register_yad_pid
{
    local pid=$1
    printf "%s\n" "$pid" >> "$YAD_PID_FILE"
}


function list_flatpaks
{
    local title=$1
    shift
    
    yad --list \
        --title="$title" \
        --class="$APP_NAME" \
        --window-icon="$FLATPAK_LOGO" \
        --no-markup \
        --grid-lines=both \
        --expand-column=0 \
        --column="ID"\
        --column="$(t LIST_COLUMN_NAME)" \
        --column="$(t LIST_COLUMN_DESCRIPTION)" \
        --column="$(t LIST_COLUMN_VERSION)" \
        --column="$(t LIST_COLUMN_BRANCH)" \
        --no-selection \
        --width=700 \
        --height=300 \
        --button="OK" \
        "$@" &
    
    local yad_pid=$!
    register_yad_pid "$yad_pid"
    
    wait "$yad_pid"
}


function list_flatpaks_for_uninstall
{
    local tmpfifo
    tmpfifo=$(create_fifo) ||
    {
        show_info "$(t TITLE_ERROR)" "$(t MSG_FAILED_START_OPERATION)"
        return 1
    }
    
    trap 'cleanup_fifo "$tmpfifo"' RETURN
    
    yad --list \
        --title="$(t FLATPAK_APP)" \
        --class="$APP_NAME" \
        --window-icon="$FLATPAK_LOGO" \
        --no-markup \
        --grid-lines=both \
        --checklist \
        --expand-column=0 \
        --column="$(t LIST_COLUMN_UNINSTALL)" \
        --column="ID" \
        --column="$(t LIST_COLUMN_NAME)" \
        --column="$(t LIST_COLUMN_DESCRIPTION)" \
        --column="$(t LIST_COLUMN_VERSION)" \
        --column="$(t LIST_COLUMN_BRANCH)" \
        --width=700 \
        --height=300 \
        --button="OK" \
        "$@" > "$tmpfifo" &
    
    local yad_pid=$!
    register_yad_pid "$yad_pid"
    
    local selections
    selections=$(<"$tmpfifo")
    
    wait "$yad_pid"
    
    [[ -z "$selections" ]] && return
    parse_selections "$selections" "uninstall"
}


function push_list_row
{
    local -n list_array=$1
    shift
    list_array+=("$1" "$2" "$3" "$4" "$5")
}


function push_checklist_row
{
    local -n checklist_array=$1
    shift
    checklist_array+=("FALSE" "$1" "$2" "$3" "$4" "$5")
}


# Recebe um callback (push_cecklist/list_row),
# o array que esse callback vai manipular e restantes
# argumentos "$@" ( search "termo" / list --app / --runtime..)
function read_flatpak_results
{
    local callback=$1
    local array=$2
    shift 2

    while IFS= read -r line
    do
        [[ $line != *$'\t'* ]] && continue
        
        IFS=$'\t' read -r application name \
            description version branch <<< "$line"
        
        "$callback" "$array" "$application" \
         "$name" "$description" "$version" "$branch"
    
    done < <(flatpak "$@" "${FLATPAK_COLUMNS[@]}")
}


function read_flatpak_results_with_loading
{
    local title=$1
    local text=$2
    shift 2
    
    {
        printf '%s\n' '#'
        read_flatpak_results "$@"
    
    } > >(yad --progress \
        --pulsate \
        --no-buttons \
        --class="$APP_NAME" \
        --window-icon="$FLATPAK_LOGO" \
        --image=gtk-refresh \
        --text="$text" \
        --auto-close \
        --title="$title" \
        --width=450)
}


function get_installed_flatpaks_for_listing
{
    local title=$1
    shift 
    
    local result_args=()
    read_flatpak_results \
    push_list_row result_args "$@"

    (( ${#result_args[@]} == 0 )) &&
    {
        show_info "$(t TITLE_NO_RESULTS)" \
        "$(t MSG_NO_FLATPAKS)"
        return
    }
    
    list_flatpaks "$title" "${result_args[@]}"
}


function get_installed_flatpaks_for_uninstalling
{
    local result_args=()
    read_flatpak_results \
    push_checklist_row result_args "${FLATPAK_LIST_APP[@]}"
    
    (( ${#result_args[@]} == 0 )) &&
    {
        show_info "$(t TITLE_NO_RESULTS)" \
        "$(t MSG_NO_FLATPAKS)"
        return
    }
    
    list_flatpaks_for_uninstall "${result_args[@]}"
}


function parse_flatpak_list_choice
{
    local title
    local listing_array=()
    
    case "$1" in
        "$(t OPTION_APPLICATIONS)")
            listing_array=("${FLATPAK_LIST_APP[@]}")
            title="$(t FLATPAK_APP)"
            ;;
        "$(t OPTION_RUNTIMES)")
            listing_array=("${FLATPAK_LIST_RUNTIME[@]}")
            title="$(t FLATPAK_RUNTIME)"
            ;;
        "$(t OPTION_BOTH)")
            listing_array=("${FLATPAK_LIST_BOTH[@]}")
            title="$(t FLATPAK_BOTH)"
            ;;
    esac
    
    get_installed_flatpaks_for_listing "$title" "${listing_array[@]}"
}


function get_flatpak_list_choice
{
    local tmpfifo
    tmpfifo=$(create_fifo) ||
    {
        show_info "$(t TITLE_ERROR)" "$(t MSG_FAILED_START_OPERATION)"
        return 1
    }
    
    trap 'cleanup_fifo "$tmpfifo"' RETURN
    
    yad --form \
        --title="$(t TITLE_CHOOSE)" \
        --class="$APP_NAME" \
        --window-icon="$FLATPAK_LOGO" \
        --fixed \
        --field="$(t MSG_CHOOSE):CB" \
        "$(t OPTION_APPLICATIONS)!$(t OPTION_RUNTIMES)!$(t OPTION_BOTH)" \
        --button="OK" \
        --button="$(t BTN_CANCEL)" > "$tmpfifo" &
    
    local yad_pid=$!
    register_yad_pid "$yad_pid"
    
    local choice
    choice=$(<"$tmpfifo")

    wait "$yad_pid"
    
    [[ -n $choice ]] &&
        parse_flatpak_list_choice "${choice%|}"
}


function run_flatpak_task
{
    local title=$1
    shift
    
    local tmpfifo
    tmpfifo=$(create_fifo) ||
    {
        show_info "$(t TITLE_ERROR)" "$(t MSG_FAILED_START_OPERATION)"
        return 1
    }
    
    trap 'cleanup_fifo "$tmpfifo"' RETURN
    
    if declare -F "$1" >/dev/null
    then
        setsid bash -c "
        source '$BASE_DIR/config/i18n'
        $(declare -f "$1")
        $1
        " > "$tmpfifo" 2>&1 &
    else
        setsid "$@" > "$tmpfifo" 2>&1 &
    fi
    
    local job_pid=$!
    
    register_task_pid "$job_pid"
    
    yad --text-info --tail \
        --title="$title" \
        --class="$APP_NAME" \
        --window-icon="$FLATPAK_LOGO" \
        --width=700 \
        --height=300 \
        --fixed \
        --button="OK" \
        --fontname="Monospace 9" \
        --scroll \
        --center < "$tmpfifo" &
    
    local yad_pid=$!
    register_yad_pid "$yad_pid"
    
    wait "$yad_pid"
    
    if kill -0 "$job_pid" 2>/dev/null
    then
        kill -TERM -"$job_pid" 2>/dev/null
        wait "$job_pid" 2>/dev/null
        sed -i "/^$job_pid$/d" "$PID_FILE" 2>/dev/null

        yad --info \
            --title="$(t TITLE_CANCELED)" \
            --class="$APP_NAME" \
            --window-icon="$FLATPAK_LOGO" \
            --text="$(t MSG_OPERATION_INTERRUPTED)" \
            --button="OK"
    else
        wait "$job_pid" 2>/dev/null
        sed -i "/^$job_pid$/d" "$PID_FILE" 2>/dev/null
    fi
}


function install_flatpaks
{
    run_flatpak_task "$(t TITLE_INSTALLING)"\
        flatpak "${FLATPAK_INSTALL_CMD[@]}" "$@"
}


function remove_flatpaks
{   
    run_flatpak_task "$(t TITLE_UNINSTALLING)" \
        flatpak "${FLATPAK_UNINSTALL_CMD[@]}" "$@"
}


function update_flatpaks
{
    run_flatpak_task "$(t TITLE_UPDATING)" \
        flatpak "${FLATPAK_UPDATE_CMD[@]}"
}


function maintenance_task_full
{
    printf "%s\n\n" "$(t MSG_START_MAINTENANCE)"
    sleep 0.1
    
    printf "%s\n" "$(t MSG_START_STAGE1)"
    if pkexec flatpak repair --system
    then
        printf "\n%s\n\n" "$(t MSG_END_STAGE1)"
    else
        printf "\n%s\n\n" "$(t MSG_IGNORED_STAGE1)"
    fi
    
    printf "\n%s\n" "$(t MSG_START_STAGE2)"
    flatpak uninstall --system --unused --assumeyes
    printf "\n%s\n" "$(t MSG_START_STAGE3_FULL)"
    flatpak uninstall --system --delete-data --assumeyes
    
    printf "\n%s\n" "$(t MSG_END_MAINTENANCE)"
}


function maintenance_task_safe
{
    printf "%s\n\n" "$(t MSG_START_MAINTENANCE)"
    sleep 0.1
    
    printf "%s\n" "$(t MSG_START_STAGE1)"
    if pkexec flatpak repair --system
    then
        printf "\n%s\n\n" "$(t MSG_END_STAGE1)"
    else
        printf "\n%s\n\n" "$(t MSG_IGNORED_STAGE1)"
    fi
    
    printf "\n%s\n" "$(t MSG_START_STAGE2)"
    flatpak uninstall --system --unused --assumeyes
    
    printf "\n%s\n" "$(t MSG_END_MAINTENANCE)"
}


function maintenance_flatpaks
{
    local tmpfifo
    tmpfifo=$(create_fifo) ||
    {
        show_info "$(t TITLE_ERROR)" "$(t MSG_FAILED_START_OPERATION)"
        return 1
    }
    
    trap 'cleanup_fifo "$tmpfifo"' RETURN
    
    yad --list \
        --radiolist \
        --title="$(t MAINTENANCE_CHOOSE_TITLE)" \
        --class="$APP_NAME" \
        --window-icon="$FLATPAK_LOGO" \
        --width=950 \
        --height=150 \
        --center \
        --fixed \
        --column="$(t MAINTENANCE_COLUMN_CHOOSE)" \
        --column="$(t MAINTENANCE_COLUMN_OPTION)" \
        --column="$(t MAINTENANCE_COLUMN_DESCRIPTION)" \
        --button="OK" \
        false "$(t MAINTENANCE_OPTION_SAFE)" "$(t MAINTENANCE_SAFE_DESCRIPTION)" \
        false "$(t MAINTENANCE_OPTION_DESTRUCTIVE)" "$(t MAINTENANCE_DESTRUCTIVE_DESCRIPTION)" > "$tmpfifo" &
    
    local yad_pid=$!
    register_yad_pid "$yad_pid"
    
    local choice
    choice=$(<"$tmpfifo")
    
    wait "$yad_pid"
    
    IFS='|' read -r _ selection _ <<< "$choice"
    
    case "${selection}" in
        "$(t MAINTENANCE_OPTION_SAFE)")
            run_flatpak_task \
                "$(t TITLE_MAINTENANCE)" \
                maintenance_task_safe
            ;;
        "$(t  MAINTENANCE_OPTION_DESTRUCTIVE)")
            run_flatpak_task \
                "$(t TITLE_MAINTENANCE)" \
                maintenance_task_full
            ;;
    esac
}


function parse_selections
{
    local flatpak_ids=()
    while IFS='|' read -r _ id _
    do
        flatpak_ids+=("$id")
    done <<< "$1"
    
    (( ${#flatpak_ids[@]} == 0 )) && return
    
    if [[ $2 == "install" ]]
    then
        install_flatpaks "${flatpak_ids[@]}"
    else
        remove_flatpaks "${flatpak_ids[@]}"
    fi
}


function show_flatpak_search_list
{
    local tmpfifo
    tmpfifo=$(create_fifo) ||
    {
        show_info "$(t TITLE_ERROR)" "$(t MSG_FAILED_START_OPERATION)"
        return 1
    }
    
    trap 'cleanup_fifo "$tmpfifo"' RETURN
    
    yad --list \
        --title="$(t FLATPAK_SEARCH_TITLE)" \
        --class="$APP_NAME" \
        --window-icon="$FLATPAK_LOGO" \
        --no-markup \
        --grid-lines=both \
        --checklist \
        --expand-column=0 \
        --column="$(t LIST_COLUMN_INSTALL)" \
        --column="ID"\
        --column="$(t LIST_COLUMN_NAME)" \
        --column="$(t LIST_COLUMN_DESCRIPTION)" \
        --column="$(t LIST_COLUMN_VERSION)"  \
        --column="$(t LIST_COLUMN_BRANCH)" \
        --width=700 \
        --height=300 \
        --button="OK" \
        "$@" > "$tmpfifo" &
    
    local yad_pid=$!
    
    register_yad_pid "$yad_pid"
    
    local selections
    selections=$(<"$tmpfifo")
    
    wait "$yad_pid"
    
    [[ -z $selections ]] && return
    parse_selections "$selections" "install"
}


function get_flatpaks_list
{
    local result_args=()
    read_flatpak_results_with_loading \
        "$(t TITLE_SEARCH_LOADING)" \
        "$(t MSG_LOADING)" \
        push_checklist_row result_args search "$1"
        
    [[ -f "$APP_ALIVE_FILE" ]] || return
    
    (( ${#result_args[@]} == 0 )) &&
    {
        show_info "$(t TITLE_NO_MATCH)" "<span $BOLD_DESCRIPTION>$(t MSG_NO_MATCH)</span>"
        return
    }
    
    show_flatpak_search_list "${result_args[@]}"
}


function validate_search_term
{
    local term=$1
    term=${term//[^[:space:][:alpha:][:digit:]]\.-/}
    read -r term _ <<< "$term"
    
    [[ -z $term ]] && return

    get_flatpaks_list "${term,,}"
}


function get_search_term
{
    # Entry provavelmente é mais apropriado,
    # mas pelo que testei o --entry não parece
    # aceitar --fixed.
    local tmpfifo
    tmpfifo=$(create_fifo) ||
    {
        show_info "$(t TITLE_ERROR)" "$(t MSG_FAILED_START_OPERATION)"
        return 1
    }
    
    trap 'cleanup_fifo "$tmpfifo"' RETURN
    
    yad --form \
        --title="$(t TITLE_SEARCH)" \
        --class="$APP_NAME" \
        --window-icon="$FLATPAK_LOGO" \
        --field="$(t MSG_SEARCH_APP)" \
        --fixed \
        --button="OK" \
        --button="$(t BTN_CANCEL)" > "$tmpfifo" &
    
    local yad_pid=$!
    register_yad_pid "$yad_pid"
    
    local term
    term=$(<"$tmpfifo")
    
    wait "$yad_pid"
    
    validate_search_term "${term%|}"
}
