#!/bin/bash


function show_info
{
    yad --title="$1" \
        --class="$APP_NAME" \
        --window-icon="$FLATPAK_LOGO" \
        --width=250 \
        --height=75 \
        --fixed \
        --text="$2" \
        --image="$ICON_INFO" \
        --button="OK"
}

function about_dialog()
{
  yad --about \
    --image="$FLATPAK_LOGO" \
    --window-icon=gtk-about \
    --class="$APP_NAME" \
    --authors="Pedro Fernandes" \
    --license="GPL3" \
    --comments="Gerenciador de Flatpaks em Bash + Yad" \
    --copyright="Copyright (c) 2025 Pedro Fernandes" \
    --pname="Flatctl" \
    --button="Fechar!gtk-close"
}
