#!/bin/bash

# SCRIPT: flatctl
# DESCRIÇÃO: Gerencia flatapks usando bash + yad
# DEPENDÊNCIAS: flatpak + yad
# AUTOR: Pedro Fernandes


BASE_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
export BASE_DIR

APP_NAME="Flatctl"
export APP_NAME

# SOURCES
source "$BASE_DIR/config/i18n"
source "$BASE_DIR/config/setup"
source "$BASE_DIR/functions/info_functions"
export -f show_info about_dialog


PID_FILE="/run/user/$UID/flatctl-active-pids"
export PID_FILE

YAD_PID_FILE="/run/user/$UID/flatctl-yad-pids"
export YAD_PID_FILE

APP_ALIVE_FILE="/run/user/$UID/flatctl.alive"
export APP_ALIVE_FILE

touch "$APP_ALIVE_FILE"


function cleanup
{
   
    [[ -f "$PID_FILE" ]] &&
    {
    
        exec 6<& 0
        exec 0< "$PID_FILE"
        
        while read -r pid
        do
            kill -TERM -"$pid" 2>/dev/null
        done
        
        exec 0<& 6
    }
    
    [[ -f "$YAD_PID_FILE" ]] &&
    {
        exec 6<& 0
        exec 0< "$YAD_PID_FILE"
    
        while read -r pid
        do
            kill -TERM "$pid" 2>/dev/null
        done
        
        exec 0<& 6
    }
    
    rm -f "$PID_FILE"
    rm -f "$YAD_PID_FILE"
    rm -f "$APP_ALIVE_FILE"
}


# TRAVA O PROGRAMA DE SER ABERTO QUANDO JÀ ESTA...ABERTO..
LOCKFILE="/run/user/$UID/flatctl.lock"

exec {lockfd}>"$LOCKFILE"
flock -n "$lockfd" ||
{
    yad --info \
        --title="Flatctl" \
        --class="$APP_NAME" \
        --window-icon="$FLATPAK_LOGO" \
        --text="$(t MSG_ALREADY_RUNNING)" \
        --fixed \
        --center \
        --button="OK"
    
    exit 0
}

trap 'cleanup; exec {lockfd}>&-' EXIT


# SOURCE FRONTEND
source "$BASE_DIR/ui/frontend"
cleanup
exit 0
